services:
 web:
  build: .
  ports:
    - "8000:8000"
  depends_on:
    - psql
  environment:
    URL_DATABASE: postgresql://postgres:password@psql:5432/blog_api
 psql:
   image: postgres
   ports:
     - "5433:5432"
   environment:
     POSTGRES_DB: "blog_api"
     POSTGRES_PASSWORD: "password"
